{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "65023f9e-c16a-4146-8d98-d3ca3aa70b70",
   "metadata": {},
   "outputs": [],
   "source": [
    "from datetime import datetime\n",
    "from random import choice\n",
    "\n",
    "\n",
    "def valida_formato_cpf(cpf):\n",
    "    # Tamanho do cpf\n",
    "    if len(cpf) != 14:\n",
    "        return False\n",
    "\n",
    "    # Verificando separadores\n",
    "    if cpf[3] != '.' or cpf[7] != '.' or cpf[11] != '-':\n",
    "        return False\n",
    "\n",
    "    # Separando em partes\n",
    "    cpf_parte1 = cpf[0:3]\n",
    "    cpf_parte2 = cpf[4:7]\n",
    "    cpf_parte3 = cpf[8:11]\n",
    "    cpf_parte4 = cpf[12:]\n",
    "\n",
    "    # Verificando todas as partes para ver se são números\n",
    "    if not (cpf_parte1.isdigit() and cpf_parte2.isdigit() and\n",
    "            cpf_parte3.isdigit() and cpf_parte4.isdigit()):\n",
    "        return False\n",
    "\n",
    "    return True\n",
    "\n",
    "def valida_cpf(cpf):\n",
    "    # Validação do primeiro digito\n",
    "    x = 10    \n",
    "    soma_1 = 0\n",
    "    for i in range(0, 11):\n",
    "        if i == 3 or i == 7:\n",
    "            continue\n",
    "        digito_atual = int(cpf[i])\n",
    "        soma_1 += digito_atual * x\n",
    "        x -= 1\n",
    "\n",
    "    resto = soma_1 % 11\n",
    "    if resto < 2:\n",
    "        digito_verificador_1 = 0\n",
    "    else:\n",
    "        digito_verificador_1 = 11 - resto\n",
    "\n",
    "    # Validação do segundo digito\n",
    "    y = 11\n",
    "    soma_2 = 0\n",
    "    \n",
    "    for i in range(0, 13):\n",
    "        if i == 3 or i == 7 or i == 11:\n",
    "            continue\n",
    "        digito_atual = int(cpf[i])\n",
    "        soma_2 += digito_atual * y\n",
    "        y -= 1\n",
    "\n",
    "    resto_2 = soma_2 % 11\n",
    "    if resto_2 < 2:\n",
    "        digito_verificador_2 = 0\n",
    "    else:\n",
    "        digito_verificador_2 = 11 - resto_2\n",
    "\n",
    "    \n",
    "    # Comparação dos digitos verificadores com o cpf de entrada\n",
    "    if digito_verificador_1 == int(cpf[12]) and digito_verificador_2 == int(cpf[13]):\n",
    "        return True\n",
    "    else:\n",
    "        return False\n",
    "    \n",
    "    \n",
    "def valida_formato_data(data):\n",
    "    # Validação do tamanho da data\n",
    "    if len(data) != 10:\n",
    "        return False\n",
    "\n",
    "    # Validação das barras\n",
    "    if data[2] != '/' or data[5] != '/':\n",
    "        return False\n",
    "\n",
    "    # Separando em partes para validar os digitos\n",
    "    dia = data[0:2]\n",
    "    mes = data[3:5]\n",
    "    ano = data[6:10]\n",
    "    \n",
    "    # Validação dos digitos\n",
    "    if not (dia.isdigit() and mes.isdigit() and ano.isdigit()):\n",
    "        return False\n",
    "\n",
    "    return True\n",
    "\n",
    "def valida_data(data):\n",
    "    hoje = datetime.now().date()\n",
    "\n",
    "    # Separando a data de nascimento\n",
    "    dia = int(data[0:2])\n",
    "    mes = int(data[3:5])\n",
    "    ano = int(data[6:10])\n",
    "\n",
    "    # Transformando números em um formato 'date'\n",
    "    data_nasc = datetime(ano, mes, dia).date()\n",
    "\n",
    "    # Verificando se é maior de idade\n",
    "    idade = hoje.year - data_nasc.year - ((hoje.month, hoje.day) < (data_nasc.month, data_nasc.day))\n",
    "\n",
    "    if idade < 18:\n",
    "        # Menor de idade!\n",
    "        return False\n",
    "    else:\n",
    "        # Maior de idade!\n",
    "        return True\n",
    "    \n",
    "def exibir_mensagem():\n",
    "    mensagens = [\"A persistência realiza o impossível\", \"Seus sonhos não precisam de plateia, eles só precisam de você\",\n",
    "                \"A persistência é o caminho do êxito\", \"No meio da dificuldade encontra-se a oportunidade\"]\n",
    "    return choice(mensagens)\n",
    "\n",
    "\n",
    "def cadastrar():\n",
    "    while True:\n",
    "        print('\\n -- Iniciando Cadastro -- \\n')\n",
    "        nome = input('Digite seu primeiro nome')\n",
    "        sobrenome = input('Digite seu sobrenome')\n",
    "        \n",
    "        # Bloco de validação de CPF\n",
    "        while True:\n",
    "            cpf = input('\\nDigite o seu CPF <formato: 123.456.789-00>')\n",
    "            if valida_formato_cpf(cpf) and valida_cpf(cpf):\n",
    "                break\n",
    "            else:\n",
    "                print('CPF inválido, por favor, digite novamente')\n",
    "                continue\n",
    "\n",
    "        # Bloco de validação da data\n",
    "        while True:\n",
    "            data_nasc = input('\\nDigite sua data de nascimento <formato: dd/mm/aaaa>')\n",
    "            if not valida_formato_data(data_nasc):\n",
    "                print('Formato de data inválido, tente novamente!')\n",
    "                continue\n",
    "            else:\n",
    "                if not valida_data(data_nasc):\n",
    "                    print('Menor de idade, cadastro cancelado.')\n",
    "                    print('Retornando ao menu principal. . .')\n",
    "                    return\n",
    "                break\n",
    "                \n",
    "        renda_bruta = float(input('\\nDigite a sua renda bruta <formato: 1234.56>'))\n",
    "\n",
    "        print('\\n' + 'Dados Cadastrados:'.center(100))\n",
    "        print(f'''\n",
    "        Nome: {nome}\n",
    "        Sobrenome: {sobrenome}\n",
    "        CPF: {cpf}\n",
    "        Data Nascimento: {data_nasc}\n",
    "        Renda Bruta: {renda_bruta}''')\n",
    "        print('----- Cadastro bem sucedido! -----'.center(100) + '\\n')\n",
    "        print('Retornando ao menu principal. . .')\n",
    "        break\n",
    "\n",
    "\n",
    "def exibir_menu():\n",
    "    while True:\n",
    "        print('''\\nMenu:\n",
    "        1 - Cadastrar\n",
    "        2 - Exibir Frase\n",
    "        3 - Sair''')\n",
    "        opcao = int(input('\\nDigite a opção desejada'))\n",
    "\n",
    "        if opcao == 1:\n",
    "            cadastrar()\n",
    "            continue\n",
    "        elif opcao == 2:\n",
    "            print('\\n' + exibir_mensagem() + '\\n')\n",
    "            continue\n",
    "        elif opcao == 3:\n",
    "            print('Bye bye!')\n",
    "            break\n",
    "        else:\n",
    "            print('Opção inválida! Tente novamente.')\n",
    "            continue"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
